#!/usr/bin/env python3


import argparse
from pdf2image import convert_from_path
from tqdm import tqdm

def remove_solutions(args, process):
    pages = [process(page) for page in tqdm(convert_from_path(args.input_filename, args.quality))]
    first, *rest = pages
    first.save(args.output_filename, "PDF", resolution=args.quality, save_all=True, append_images=rest)

def remove_colorful(page):
    page = page.copy()
    sat = page.convert('HSV').split()[1].load()
    page_mod = page.load()
    for i in range(page.size[0]): # for every pixel:
        for j in range(page.size[1]):
            if sat[i, j] > 10:
                page_mod[i,j] = (255, 255, 255)
    return page

def main():
    parser = argparse.ArgumentParser(description='remove solutions from an exam')
    parser.add_argument('input_filename', type=str, help='the file with solutions')
    parser.add_argument('output_filename', type=str, help='the location to put the file without solutions')
    parser.add_argument('--quality', type=int, default=100, help='the resolution of the output in dpi ')
    return remove_solutions(parser.parse_args(), remove_colorful)

if __name__ == '__main__':
    main()
